
// Code generated by stanc v2.30.1
#include <stan/model/model_header.hpp>
namespace mixed_model_1_variable_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 23> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 9, column 4 to column 15)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 10, column 4 to column 17)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 11, column 4 to column 18)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 12, column 4 to column 27)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 13, column 4 to column 22)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 16, column 4 to column 25)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 18, column 8 to column 61)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 17, column 17 to line 19, column 5)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 17, column 4 to line 19, column 5)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 20, column 4 to column 27)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 21, column 4 to column 38)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 22, column 4 to column 31)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 23, column 4 to column 28)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 2, column 4 to column 21)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 3, column 4 to column 10)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 4, column 11 to column 12)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 4, column 4 to column 14)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 5, column 13 to column 14)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 5, column 4 to column 16)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 6, column 15 to column 16)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 6, column 4 to column 18)",
 " (in '/Users/jmb20210028/my_dev/stan_code_storage/scripts/stan_code/mixed_model_1_variable.stan', line 10, column 14 to column 15)"};




class mixed_model_1_variable_model final : public model_base_crtp<mixed_model_1_variable_model> {

 private:
  int N;
  int G;
  std::vector<double> y;
  std::vector<double> x_1;
  std::vector<int> teamID; 
  
 
 public:
  ~mixed_model_1_variable_model() { }
  
  inline std::string model_name() const final { return "mixed_model_1_variable_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.30.1", "stancflags = "};
  }
  
  
  mixed_model_1_variable_model(stan::io::var_context& context__,
                               unsigned int random_seed__ = 0,
                               std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "mixed_model_1_variable_model_namespace::mixed_model_1_variable_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 14;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 14;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 15;
      context__.validate_dims("data initialization","G","int",
           std::vector<size_t>{});
      G = std::numeric_limits<int>::min();
      
      
      current_statement__ = 15;
      G = context__.vals_i("G")[(1 - 1)];
      current_statement__ = 16;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 17;
      context__.validate_dims("data initialization","y","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      y = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 17;
      y = context__.vals_r("y");
      current_statement__ = 18;
      stan::math::validate_non_negative_index("x_1", "N", N);
      current_statement__ = 19;
      context__.validate_dims("data initialization","x_1","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      x_1 = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 19;
      x_1 = context__.vals_r("x_1");
      current_statement__ = 20;
      stan::math::validate_non_negative_index("teamID", "N", N);
      current_statement__ = 21;
      context__.validate_dims("data initialization","teamID","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      teamID = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 21;
      teamID = context__.vals_i("teamID");
      current_statement__ = 22;
      stan::math::validate_non_negative_index("beta", "G", G);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + G + 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "mixed_model_1_variable_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read<local_scalar_t__>();
      std::vector<local_scalar_t__> beta =
         std::vector<local_scalar_t__>(G, DUMMY_VAR__);
      current_statement__ = 2;
      beta = in__.template read<std::vector<local_scalar_t__>>(G);
      local_scalar_t__ beta_fix = DUMMY_VAR__;
      current_statement__ = 3;
      beta_fix = in__.template read<local_scalar_t__>();
      local_scalar_t__ tau_beta = DUMMY_VAR__;
      current_statement__ = 4;
      tau_beta = in__.template read_constrain_lb<local_scalar_t__, 
                   jacobian__>(0, lp__);
      local_scalar_t__ s_y = DUMMY_VAR__;
      current_statement__ = 5;
      s_y = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      {
        current_statement__ = 6;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(s_y, 0, 100));
        current_statement__ = 9;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 7;
          lp_accum__.add(
            stan::math::normal_lpdf<propto__>(
              stan::model::rvalue(y, "y", stan::model::index_uni(i)),
              (alpha +
                (stan::model::rvalue(beta, "beta",
                   stan::model::index_uni(stan::model::rvalue(teamID,
                                            "teamID",
                                            stan::model::index_uni(i)))) *
                  stan::model::rvalue(x_1, "x_1", stan::model::index_uni(i)))),
              s_y));
        }
        current_statement__ = 10;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha, 0, 100));
        current_statement__ = 11;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(beta, beta_fix, tau_beta));
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_fix, 0, 100));
        current_statement__ = 13;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(tau_beta, 0, 5));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "mixed_model_1_variable_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read<local_scalar_t__>();
      std::vector<double> beta =
         std::vector<double>(G, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta = in__.template read<std::vector<local_scalar_t__>>(G);
      double beta_fix = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      beta_fix = in__.template read<local_scalar_t__>();
      double tau_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      tau_beta = in__.template read_constrain_lb<local_scalar_t__, 
                   jacobian__>(0, lp__);
      double s_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      s_y = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      out__.write(alpha);
      out__.write(beta);
      out__.write(beta_fix);
      out__.write(tau_beta);
      out__.write(s_y);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ alpha = DUMMY_VAR__;
      alpha = in__.read<local_scalar_t__>();
      out__.write(alpha);
      std::vector<local_scalar_t__> beta =
         std::vector<local_scalar_t__>(G, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        beta[(sym1__ - 1)] = in__.read<local_scalar_t__>();
      }
      out__.write(beta);
      local_scalar_t__ beta_fix = DUMMY_VAR__;
      beta_fix = in__.read<local_scalar_t__>();
      out__.write(beta_fix);
      local_scalar_t__ tau_beta = DUMMY_VAR__;
      tau_beta = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, tau_beta);
      local_scalar_t__ s_y = DUMMY_VAR__;
      s_y = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_y);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"alpha", "beta", "beta_fix",
      "tau_beta", "s_y"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(G)}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "beta_fix");
    param_names__.emplace_back(std::string() + "tau_beta");
    param_names__.emplace_back(std::string() + "s_y");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "beta_fix");
    param_names__.emplace_back(std::string() + "tau_beta");
    param_names__.emplace_back(std::string() + "s_y");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(G) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"beta_fix\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_y\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(G) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"beta_fix\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_y\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + G) + 1) + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + G) + 1) + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 5> names__{"alpha", "beta",
      "beta_fix", "tau_beta", "s_y"};
      const std::array<Eigen::Index, 5> constrain_param_sizes__{1, G, 
       1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}

using stan_model = mixed_model_1_variable_model_namespace::mixed_model_1_variable_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return mixed_model_1_variable_model_namespace::profiles__;
}

#endif


